remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title:
logo: https://static.wixstatic.com/media/c6cff5_dd7659693c6247dc8eb8605d3dca95e8~mv2_d_3300_2550_s_4_2.png/v1/crop/x_1058,y_575,w_1183,h_1225/fill/w_288,h_298,al_c,usm_0.66_1.00_0.01/c6cff5_dd7659693c6247dc8eb8605d3dca95e8~mv2_d_3300_2550_s_4_2.png
description: Gravity is c++ modeling tool for mathematical optimization and machine learning.
show_downloads: true
google_analytics:
